services:
  mlflow-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mlflow-server
    networks:
      - internal_network
    ports:
      - "10.8.0.1:5000:5000" # 綁定到 VPN 的內網 IP
    volumes:
      - ./mlflow:/mlflow # 資料掛載目錄
    command: >
      mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri postgresql://postgres:password@db:5432/mlflow --default-artifact-root /mlflow/mlruns
    environment:
      - MLFLOW_TRACKING_URI=http://10.8.0.1:5000 # 設定 MLflow 跟蹤 URI
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mlflow
    volumes:
      - ./mlflow/db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal_network

      

networks:
  internal_network:
    driver: bridge
